import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import 'react-day-picker/dist/style.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          background: `
            radial-gradient(circle at 30% 30%, rgba(37, 99, 235, 0.4), transparent 70%),
            radial-gradient(circle at 70% 70%, rgba(30, 64, 175, 0.5), transparent 70%),
            linear-gradient(135deg, #2563EB 0%, #1E40AF 100%)
          `,
          backgroundBlendMode: "overlay, overlay, normal",
          color: "#fff",
          fontFamily: "var(--font-geist-sans)",
        }}
      >

        {children}
      </body>
    </html>
  );
}
